# Create here the Drupal site you would like
version: '2'
services:
  # memcached service disabled until Amazee resolves https://github.com/amazeeio/docker/issues/2
  #memcached:
  #  hostname: memcache.docker.amazee.io
  #  image: sameersbn/memcached:latest
  #  ports:
  #    - "11211:11211"
  #  restart: always

  drupal:
    # Choose your URL and hostname for this Docker Container
    # NEEDS to end with '.docker.amazee.io' !
    # DO NOT remove the '&hostname'
    hostname: &hostname thecast.docker.amazee.io

    environment:
      WEBROOT: public
      # If you would like to use blackfire.io, uncomment and add your server credentials:
      #BLACKFIRE_SERVER_ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      #BLACKFIRE_SERVER_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

      # APC Support is by default enabled, but in some cases it can make issues, change to 0 to disable:
      APC: 1


################################################
### Do not change anything below here, unless you know what you do
      VIRTUAL_HOST: *hostname
    image: amazeeio/drupal:php56-basic
    #image: amazeeio/drupal:php70-basic
    volumes:
      - .:/var/www/drupal/public_html
    volumes_from:
      - container:amazeeio-ssh-agent
    container_name: *hostname
    network_mode: bridge
    ports:
      - "3306"
