<?php
/**
 * @file
 * Code for the Cast Beans feature.
 */

include_once 'cast_beans.features.inc';

/**
 * Implements hook_preprocess_HOOK().
 *
 * If a link field has a URL but no title, don't display it.
 */
function cast_beans_preprocess_field(&$variables) {
  if ($variables['element']['#field_name'] == 'field_button') {
    if (isset($variables['element']['#items'][0])) {
      $field_value = $variables['element']['#items'][0];
      // Title and URL are identical if title is missing.
      if ($field_value['title'] == $field_value['url']) {
        $variables['items'][0]['#markup'] = '';

      }
    }
    else {
      $one = 'two';
    }

  }
}