<?php
/**
 * @file
 * Code for the Cast Boxes feature.
 */

include_once 'cast_boxes.features.inc';

/**
 * Implements hook_menu_alter().
 *
 * - Unset entity_boxes' add links; they're confusing while we transition to Bean.
 */
function cast_boxes_menu_alter(&$items) {
  $keys = array_keys($items);
  foreach ($keys as $key) {
    if (strpos($key, 'admin/structure/block/box-add') === 0) {
      unset($items[$key]);
    }
  }
}
