<?php

// @update hooks for cast core content types, contexts, display modes, etc.

/**
 * Enable mediaelement module.
 */
function cast_core_types_update_7000() {
    module_enable(array('mediaelement'));
}

/**
 * Enable cast_misc module.
 */
function cast_core_types_update_7001() {
  module_enable(array('cast_misc', 'cast_contact', 'cast_media'));
}

/**
 * Enable scheduler module.
 */
function cast_core_types_update_7002() {
  module_enable(array('scheduler'));
}
